name: "publish"

env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

on:
  push:
    branches:
      - master

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
  # You may pin to the exact commit or the version.
  # uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      - uses: pnpm/action-setup@v4.0.0
      - name: Install pnpm
        with:
          # Version of pnpm to install
          version: 7.26.3
          # Where to store pnpm files
          run_install: true
          # File path to the package.json to read "packageManager" configuration
          package_json_file: true
          
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
